//Window>-specific>
#ifdef _WINDOWS
// Add> C> includes> here>

// Add> C>++ includes> here>
#if defined __cplusplus

//Find memory leaks.
//#include "../../afxmem.h"
//#ifdef _DEBUG
//#define new DEBUG_NEW
//#endif

#include <QtGui/QApplication> // #include <QtGui/Qt> includes>
#include <QtGui/QPushButton>
#include <QtGui/QAbstractButton>
#include <QtGui/QAbstractGraphicsShapeItem>
#include <QtGui/QAbstractItemDelegate>
#include <QtGui/QAbstractItemView>
#include <QtGui/QAbstractPageSetupDialog>
#include <QtGui/QAbstractPrintDialog>
#include <QtGui/QAbstractProxyModel>
#include <QtGui/QAbstractScrollArea>
#include <QtGui/QAbstractSlider>
#include <QtGui/QAbstractSpinBox>
#include <QtGui/QAbstractTextDocumentLayout>
#include <QtGui/QAbstractUndoItem>
#include <QtGui/QAccessible>
#include <QtGui/QAccessible2Interface>
#include <QtGui/QAccessibleApplication>
#include <QtGui/QAccessibleBridge>
#include <QtGui/QAccessibleBridgeFactoryInterface>
#include <QtGui/QAccessibleBridgePlugin>
#include <QtGui/QAccessibleEditableTextInterface>
#include <QtGui/QAccessibleEvent>
#include <QtGui/QAccessibleFactoryInterface>
#include <QtGui/QAccessibleInterface>
#include <QtGui/QAccessibleInterfaceEx>
#include <QtGui/QAccessibleObject>
#include <QtGui/QAccessibleObjectEx>
#include <QtGui/QAccessiblePlugin>
#include <QtGui/QAccessibleSimpleEditableTextInterface>
#include <QtGui/QAccessibleTableInterface>
#include <QtGui/QAccessibleTextInterface>
#include <QtGui/QAccessibleValueInterface>
#include <QtGui/QAccessibleWidget>
#include <QtGui/QAccessibleWidgetEx>
#include <QtGui/QAction>
#include <QtGui/QActionEvent>
#include <QtGui/QActionGroup>
#include <QtGui/QApplication>
#include <QtGui/QBitmap>
#include <QtGui/QBoxLayout>
#include <QtGui/QBrush>
#include <QtGui/QBrushData>
#include <QtGui/QButtonGroup>
#include <QtGui/QCalendarWidget>
#include <QtGui/QCDEStyle>
#include <QtGui/QCheckBox>
#include <QtGui/QCleanlooksStyle>
#include <QtGui/QClipboard>
#include <QtGui/QClipboardEvent>
#include <QtGui/QCloseEvent>
#include <QtGui/QColor>
#include <QtGui/QColorDialog>
#include <QtGui/QColorGroup>
#include <QtGui/QColormap>
#include <QtGui/QColumnView>
#include <QtGui/QComboBox>
#include <QtGui/QCommandLinkButton>
#include <QtGui/QCommonStyle>
#include <QtGui/QCompleter>
#include <QtGui/QConicalGradient>
#include <QtGui/QContextMenuEvent>
#include <QtGui/QCursor>
#include <QtGui/QCursorShape>
#include <QtGui/QDataWidgetMapper>
#include <QtGui/QDateEdit>
#include <QtGui/QDateTimeEdit>
#include <QtGui/QDesktopServices>
#include <QtGui/QDesktopWidget>
#include <QtGui/QDial>
#include <QtGui/QDialog>
#include <QtGui/QDialogButtonBox>
#include <QtGui/QDirModel>
#include <QtGui/QDockWidget>
#include <QtGui/QDoubleSpinBox>
#include <QtGui/QDoubleValidator>
#include <QtGui/QDrag>
#include <QtGui/QDragEnterEvent>
#include <QtGui/QDragLeaveEvent>
#include <QtGui/QDragMoveEvent>
#include <QtGui/QDragResponseEvent>
#include <QtGui/QDropEvent>
#include <QtGui/QErrorMessage>
#include <QtGui/QFileDialog>
#include <QtGui/QFileIconProvider>
#include <QtGui/QFileOpenEvent>
#include <QtGui/QFileSystemModel>
#include <QtGui/QFocusEvent>
#include <QtGui/QFocusFrame>
#include <QtGui/QFont>
#include <QtGui/QFontComboBox>
#include <QtGui/QFontDatabase>
#include <QtGui/QFontDialog>
#include <QtGui/QFontInfo>
#include <QtGui/QFontMetrics>
#include <QtGui/QFontMetricsF>
#include <QtGui/QFormLayout>
#include <QtGui/QFrame>
#include <QtGui/QGradient>
#include <QtGui/QGradientStop>
#include <QtGui/QGradientStops>
#include <QtGui/QGraphicsEllipseItem>
#include <QtGui/QGraphicsGridLayout>
#include <QtGui/QGraphicsItem>
#include <QtGui/QGraphicsItemAnimation>
#include <QtGui/QGraphicsItemGroup>
#include <QtGui/QGraphicsLayout>
#include <QtGui/QGraphicsLayoutItem>
#include <QtGui/QGraphicsLinearLayout>
#include <QtGui/QGraphicsLineItem>
#include <QtGui/QGraphicsPathItem>
#include <QtGui/QGraphicsPixmapItem>
#include <QtGui/QGraphicsPolygonItem>
#include <QtGui/QGraphicsProxyWidget>
#include <QtGui/QGraphicsRectItem>
#include <QtGui/QGraphicsScene>
#include <QtGui/QGraphicsSceneContextMenuEvent>
#include <QtGui/QGraphicsSceneDragDropEvent>
#include <QtGui/QGraphicsSceneEvent>
#include <QtGui/QGraphicsSceneHelpEvent>
#include <QtGui/QGraphicsSceneHoverEvent>
#include <QtGui/QGraphicsSceneMouseEvent>
#include <QtGui/QGraphicsSceneMoveEvent>
#include <QtGui/QGraphicsSceneResizeEvent>
#include <QtGui/QGraphicsSceneWheelEvent>
#include <QtGui/QGraphicsSimpleTextItem>
#include <QtGui/QGraphicsTextItem>
#include <QtGui/QGraphicsView>
#include <QtGui/QGraphicsWidget>
#include <QtGui/QGridLayout>
#include <QtGui/QGroupBox>
#include <QtGui/QGtkStyle>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QHelpEvent>
#include <QtGui/QHideEvent>
#include <QtGui/QHoverEvent>
#include <QtGui/QIcon>
#include <QtGui/QIconDragEvent>
#include <QtGui/QIconEngine>
#include <QtGui/QIconEngineFactoryInterface>
#include <QtGui/QIconEngineFactoryInterfaceV2>
#include <QtGui/QIconEnginePlugin>
#include <QtGui/QIconEnginePluginV2>
#include <QtGui/QIconEngineV2>
#include <QtGui/QIconSet>
#include <QtGui/QImage>
#include <QtGui/QImageIOHandler>
#include <QtGui/QImageIOHandlerFactoryInterface>
#include <QtGui/QImageIOPlugin>
#include <QtGui/QImageReader>
#include <QtGui/QImageTextKeyLang>
#include <QtGui/QImageWriter>
#include <QtGui/QInputContext>
#include <QtGui/QInputContextFactory>
#include <QtGui/QInputContextFactoryInterface>
#include <QtGui/QInputContextPlugin>
#include <QtGui/QInputDialog>
#include <QtGui/QInputEvent>
#include <QtGui/QInputMethodEvent>
#include <QtGui/QIntValidator>
#include <QtGui/QItemDelegate>
#include <QtGui/QItemEditorCreator>
#include <QtGui/QItemEditorCreatorBase>
#include <QtGui/QItemEditorFactory>
#include <QtGui/QItemSelection>
#include <QtGui/QItemSelectionModel>
#include <QtGui/QItemSelectionRange>
#include <QtGui/QKeyEvent>
#include <QtGui/QKeySequence>
#include <QtGui/QLabel>
#include <QtGui/QLayout>
#include <QtGui/QLayoutItem>
#include <QtGui/QLayoutIterator>
#include <QtGui/QLCDNumber>
#include <QtGui/QLinearGradient>
#include <QtGui/QLineEdit>
#include <QtGui/QListView>
#include <QtGui/QListWidget>
#include <QtGui/QListWidgetItem>
#include <QtGui/QMacMime>
#include <QtGui/QMacPasteboardMime>
#include <QtGui/QMainWindow>
#include <QtGui/QMatrix>
#include <QtGui/QMdiArea>
#include <QtGui/QMdiSubWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QMenubarUpdatedEvent>
#include <QtGui/QMenuItem>
#include <QtGui/QMessageBox>
#include <QtGui/QMimeSource>
#include <QtGui/QMotifStyle>
#include <QtGui/QMouseEvent>
#include <QtGui/QMoveEvent>
#include <QtGui/QMovie>
#include <QtGui/QPageSetupDialog>
#include <QtGui/QPaintDevice>
#include <QtGui/QPaintEngine>
#include <QtGui/QPaintEngineState>
#include <QtGui/QPainter>
#include <QtGui/QPainterPath>
#include <QtGui/QPainterPathPrivate>
#include <QtGui/QPainterPathStroker>
#include <QtGui/QPaintEvent>
#include <QtGui/QPalette>
#include <QtGui/QPen>
#include <QtGui/QPicture>
#include <QtGui/QPictureFormatInterface>
#include <QtGui/QPictureFormatPlugin>
#include <QtGui/QPictureIO>
#include <QtGui/QPixmap>
#include <QtGui/QPixmapCache>
#include <QtGui/QPlainTextDocumentLayout>
#include <QtGui/QPlainTextEdit>
#include <QtGui/QPlastiQueStyle>
#include <QtGui/QPolygon>
#include <QtGui/QPolygonF>
#include <QtGui/QPrintDialog>
#include <QtGui/QPrintEngine>
#include <QtGui/QPrinter>
#include <QtGui/QPrinterInfo>
#include <QtGui/QPrintPreviewDialog>
#include <QtGui/QPrintPreviewWidget>
#include <QtGui/QProgressBar>
#include <QtGui/QProgressDialog>
#include <QtGui/QProxyModel>
#include <QtGui/QPushButton>
#include <QtGui/QRadialGradient>
#include <QtGui/QRadioButton>
#include <QtGui/QRegExpValidator>
#include <QtGui/QRegion>
#include <QtGui/QResizeEvent>
#include <QtGui/QRgb>
#include <QtGui/QRubberBand>
#include <QtGui/QScrollArea>
#include <QtGui/QScrollBar>
#include <QtGui/QSessionManager>
#include <QtGui/QShortcut>
#include <QtGui/QShortcutEvent>
#include <QtGui/QShowEvent>
#include <QtGui/QSizeGrip>
#include <QtGui/QSizePolicy>
#include <QtGui/QSlider>
#include <QtGui/QSortFilterProxyModel>
#include <QtGui/QSound>
#include <QtGui/QSpacerItem>
#include <QtGui/QSpinBox>
#include <QtGui/QSplashScreen>
#include <QtGui/QSplitter>
#include <QtGui/QSplitterHandle>
#include <QtGui/QStackedLayout>
#include <QtGui/QStackedWidget>
#include <QtGui/QStandardItem>
#include <QtGui/QStandardItemEditorCreator>
#include <QtGui/QStandardItemModel>
#include <QtGui/QStatusBar>
#include <QtGui/QStatusTipEvent>
#include <QtGui/QStringListModel>
#include <QtGui/QStyle>
#include <QtGui/QStyledItemDelegate>
#include <QtGui/QStyleFactory>
#include <QtGui/QStyleFactoryInterface>
#include <QtGui/QStyleHintReturn>
#include <QtGui/QStyleHintReturnMask>
#include <QtGui/QStyleHintReturnVariant>
#include <QtGui/QStyleOption>
#include <QtGui/QStyleOptionButton>
#include <QtGui/QStyleOptionComboBox>
#include <QtGui/QStyleOptionComplex>
#include <QtGui/QStyleOptionDockWidget>
#include <QtGui/QStyleOptionDockWidgetV2>
#include <QtGui/QStyleOptionFocusRect>
#include <QtGui/QStyleOptionFrame>
#include <QtGui/QStyleOptionFrameV2>
#include <QtGui/QStyleOptionFrameV3>
#include <QtGui/QStyleOptionGraphicsItem>
#include <QtGui/QStyleOptionGroupBox>
#include <QtGui/QStyleOptionHeader>
#include <QtGui/QStyleOptionMenuItem>
#include <QtGui/QStyleOptionProgressBar>
#include <QtGui/QStyleOptionProgressBarV2>
#include <QtGui/QStyleOptionQ3DockWindow>
#include <QtGui/QStyleOptionQ3ListView>
#include <QtGui/QStyleOptionQ3ListViewItem>
#include <QtGui/QStyleOptionRubberBand>
#include <QtGui/QStyleOptionSizeGrip>
#include <QtGui/QStyleOptionSlider>
#include <QtGui/QStyleOptionSpinBox>
#include <QtGui/QStyleOptionTab>
#include <QtGui/QStyleOptionTabBarBase>
#include <QtGui/QStyleOptionTabBarBaseV2>
#include <QtGui/QStyleOptionTabV2>
#include <QtGui/QStyleOptionTabV3>
#include <QtGui/QStyleOptionTabWidgetFrame>
#include <QtGui/QStyleOptionTitleBar>
#include <QtGui/QStyleOptionToolBar>
#include <QtGui/QStyleOptionToolBox>
#include <QtGui/QStyleOptionToolBoxV2>
#include <QtGui/QStyleOptionToolButton>
#include <QtGui/QStyleOptionViewItem>
#include <QtGui/QStyleOptionViewItemV2>
#include <QtGui/QStyleOptionViewItemV3>
#include <QtGui/QStyleOptionViewItemV4>
#include <QtGui/QStylePainter>
#include <QtGui/QStylePlugin>
#include <QtGui/QSyntaxHighlighter>
#include <QtGui/QSystemTrayIcon>
#include <QtGui/QTabBar>
#include <QtGui/QTabletEvent>
#include <QtGui/QTableView>
#include <QtGui/QTableWidget>
#include <QtGui/QTableWidgetItem>
#include <QtGui/QTableWidgetSelectionRange>
#include <QtGui/QTabWidget>
#include <QtGui/QtEvents>
#include <QtGui/QTextBlock>
#include <QtGui/QTextBlockFormat>
#include <QtGui/QTextBlockGroup>
#include <QtGui/QTextBlockUserData>
#include <QtGui/QTextBrowser>
#include <QtGui/QTextCharFormat>
#include <QtGui/QTextCursor>
#include <QtGui/QTextDocument>
#include <QtGui/QTextDocumentFragment>
#include <QtGui/QTextDocumentWriter>
#include <QtGui/QTextEdit>
#include <QtGui/QTextFormat>
#include <QtGui/QTextFragment>
#include <QtGui/QTextFrame>
#include <QtGui/QTextFrameFormat>
#include <QtGui/QTextFrameLayoutData>
#include <QtGui/QTextImageFormat>
#include <QtGui/QTextInlineObject>
#include <QtGui/QTextItem>
#include <QtGui/QTextLayout>
#include <QtGui/QTextLength>
#include <QtGui/QTextLine>
#include <QtGui/QTextList>
#include <QtGui/QTextListFormat>
#include <QtGui/QTextObject>
#include <QtGui/QTextObjectInterface>
#include <QtGui/QTextOption>
#include <QtGui/QTextTable>
#include <QtGui/QTextTableCell>
#include <QtGui/QTextTableCellFormat>
#include <QtGui/QTextTableFormat>
#include <QtGui/QTimeEdit>
#include <QtGui/QToolBar>
#include <QtGui/QToolBarChangeEvent>
#include <QtGui/QToolBox>
#include <QtGui/QToolButton>
#include <QtGui/QToolTip>
#include <QtGui/QTransform>
#include <QtGui/QTreeView>
#include <QtGui/QTreeWidget>
#include <QtGui/QTreeWidgetItem>
#include <QtGui/QTreeWidgetItemIterator>
#include <QtGui/QUndoCommand>
#include <QtGui/QUndoGroup>
#include <QtGui/QUndoStack>
#include <QtGui/QUndoView>
#include <QtGui/QUnixPrintWidget>
#include <QtGui/QUpdateLaterEvent>
#include <QtGui/QValidator>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWhatsThis>
#include <QtGui/QWhatsThisClickedEvent>
#include <QtGui/QWheelEvent>
#include <QtGui/QWidget>
#include <QtGui/QWidgetAction>
#include <QtGui/QWidgetData>
#include <QtGui/QWidgetItem>
#include <QtGui/QWidgetItemV2>
#include <QtGui/QWidgetList>
#include <QtGui/QWidgetMapper>
#include <QtGui/QWidgetSet>
#include <QtGui/QWindowsCEStyle>
#include <QtGui/QWindowsMime>
#include <QtGui/QWindowsMobileStyle>
#include <QtGui/QWindowsStyle>
#include <QtGui/QWindowStateChangeEvent>
#include <QtGui/QWindowsVistaStyle>
#include <QtGui/QWindowsXPStyle>
#include <QtGui/QWizard>
#include <QtGui/QWizardPage>
#include <QtGui/QWMatrix>
#include <QtGui/QWorkspace>

//02>25>2009>  02>:35> PM>             5>,593> <QtGui/QtGui/>

#include <QtCore/QAbstractEventDispatcher>
#include <QtCore/QAbstractFileEngine>
#include <QtCore/QAbstractFileEngineHandler>
#include <QtCore/QAbstractFileEngineIterator>
#include <QtCore/QAbstractItemModel>
#include <QtCore/QAbstractListModel>
#include <QtCore/QAbstractTableModel>
#include <QtCore/QArgument>
#include <QtCore/QAtomicInt>
#include <QtCore/QAtomicPointer>
#include <QtCore/QBasicAtomicInt>
#include <QtCore/QBasicAtomicPointer>
#include <QtCore/QBasicTimer>
#include <QtCore/QBitArray>
#include <QtCore/QBitRef>
#include <QtCore/QBool>
#include <QtCore/QBuffer>
#include <QtCore/QByteArray>
#include <QtCore/QByteArrayMatcher>
#include <QtCore/QByteRef>
#include <QtCore/QCache>
#include <QtCore/QChar>
#include <QtCore/QCharRef>
#include <QtCore/QChildEvent>
#include <QtCore/QConstString>
#include <QtCore/QCOORD>
#include <QtCore/QCoreApplication>
#include <QtCore/QCryptographicHash>
#include <QtCore/QCustomEvent>
#include <QtCore/QDataStream>
#include <QtCore/QDate>
#include <QtCore/QDateTime>
#include <QtCore/QDebug>
#include <QtCore/QDir>
#include <QtCore/QDirIterator>
#include <QtCore/QDynamicPropertyChangeEvent>
#include <QtCore/QEvent>
#include <QtCore/QEventLoop>
#include <QtCore/QExplicitlySharedDataPointer>
#include <QtCore/QFactoryInterface>
#include <QtCore/QFile>
#include <QtCore/QFileInfo>
#include <QtCore/QFileInfoList>
#include <QtCore/QFileInfoListIterator>
#include <QtCore/QFileSystemWatcher>
#include <QtCore/QFlag>
#include <QtCore/QFlags>
#include <QtCore/QForeachContainer>
#include <QtCore/QForeachContainerBase>
#include <QtCore/QFSFileEngine>
#include <QtCore/QFuture>
#include <QtCore/QFutureInterface>
#include <QtCore/QFutureInterfaceBase>
#include <QtCore/QFutureIterator>
#include <QtCore/QFutureSynchronizer>
#include <QtCore/QFutureWatcher>
#include <QtCore/QFutureWatcherBase>
#include <QtCore/QGenericArgument>
#include <QtCore/QGenericReturnArgument>
#include <QtCore/QGlobalStatic>
#include <QtCore/QGlobalStaticDeleter>
#include <QtCore/QHash>
#include <QtCore/QHashData>
#include <QtCore/QHashDummyNode>
#include <QtCore/QHashDummyValue>
#include <QtCore/QHashIterator>
#include <QtCore/QHashNode>
#include <QtCore/QIncompatibleFlag>
#include <QtCore/QInternal>

#if QT_VERSION >= 0x040600//VOXOX CHANGE by Rolando - 2010.01.03 
#include <QtCore/QIntegerForSize>//VOXOX CHANGE by Rolando 12.29.09 - changed filename to QIntegerForSize instead of QIntForSize   
#else//VOXOX CHANGE by Rolando - 2010.01.03 
#include <QtCore/QIntForSize>
#include <QtCore/QIntForType>
#endif

#include <QtCore/QIODevice>
#include <QtCore/QLatin1Char>
#include <QtCore/QLatin1String>
#include <QtCore/QLibrary>
#include <QtCore/QLibraryInfo>
#include <QtCore/QLine>
#include <QtCore/QLineF>
#include <QtCore/QLinkedList>
#include <QtCore/QLinkedListData>
#include <QtCore/QLinkedListIterator>
#include <QtCore/QLinkedListNode>
#include <QtCore/QList>
#include <QtCore/QListData>
#include <QtCore/QListIterator>
#include <QtCore/QLocale>
#include <QtCore/QMap>
#include <QtCore/QMapData>
#include <QtCore/QMapIterator>
#include <QtCore/QMapNode>
#include <QtCore/QMapPayloadNode>
#include <QtCore/QMetaClassInfo>
#include <QtCore/QMetaEnum>
#include <QtCore/QMetaMethod>
#include <QtCore/QMetaObject>
#include <QtCore/QMetaObjectExtraData>
#include <QtCore/QMetaProperty>
#include <QtCore/QMetaType>
#include <QtCore/QMetaTypeId>
#include <QtCore/QMetaTypeId2>
#include <QtCore/QMimeData>
#include <QtCore/QModelIndex>
#include <QtCore/QModelIndexList>
#include <QtCore/QMultiHash>
#include <QtCore/QMultiMap>
#include <QtCore/QMutableFutureIterator>
#include <QtCore/QMutableHashIterator>
#include <QtCore/QMutableLinkedListIterator>
#include <QtCore/QMutableListIterator>
#include <QtCore/QMutableMapIterator>
#include <QtCore/QMutableSetIterator>
#include <QtCore/QMutableStringListIterator>
#include <QtCore/QMutableVectorIterator>
#include <QtCore/QMutex>
#include <QtCore/QMutexLocker>
#include <QtCore/QNoDebug>
#include <QtCore/QNoImplicitBoolCast>
#include <QtCore/QObject>
#include <QtCore/QObjectCleanupHandler>
#include <QtCore/QObjectData>
#include <QtCore/QObjectList>
#include <QtCore/QObjectUserData>
#include <QtCore/QPair>
#include <QtCore/QPersistentModelIndex>
#include <QtCore/QPluginLoader>
#include <QtCore/QPoint>
#include <QtCore/QPointer>
#include <QtCore/QPointF>
#include <QtCore/QProcess>
#include <QtCore/QQueue>
#include <QtCore/QReadLocker>
#include <QtCore/QReadWriteLock>
#include <QtCore/QRect>
#include <QtCore/QRectF>
#include <QtCore/QRegExp>
#include <QtCore/QResource>
#include <QtCore/QReturnArgument>
#include <QtCore/QRunnable>
#include <QtCore/QSemaphore>
#include <QtCore/QSet>
#include <QtCore/QSetIterator>
#include <QtCore/QSettings>
#include <QtCore/QSharedData>
#include <QtCore/QSharedDataPointer>
#include <QtCore/QSharedMemory>
#include <QtCore/QSharedPointer>
#include <QtCore/QSignalMapper>
#include <QtCore/QSize>
#include <QtCore/QSizeF>
#include <QtCore/QSocketNotifier>
#include <QtCore/QStack>
#include <QtCore/QStdWString>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QStringListIterator>
#include <QtCore/QStringMatcher>
#include <QtCore/QStringRef>
#include <QtCore/QSysInfo>
#include <QtCore/QSystemLocale>
#include <QtCore/QSystemSemaphore>
#include <QtCore/Qt>
#include <QtCore/QtAlgorithms>
#include <QtCore/QtCleanUpFunction>
#include <QtCore/QtConcurrentFilter>
#include <QtCore/QtConcurrentMap>
#include <QtCore/QtConcurrentRun>
#include <QtCore/QtContainerFwd>
#include <QtCore/QtDebug>
#include <QtCore/QTemporaryFile>
#include <QtCore/QtEndian>
#include <QtCore/QTextBoundaryFinder>
#include <QtCore/QTextCodec>
#include <QtCore/QTextCodecFactoryInterface>
#include <QtCore/QTextCodecPlugin>
#include <QtCore/QTextDecoder>
#include <QtCore/QTextEncoder>
#include <QtCore/QTextIStream>
#include <QtCore/QTextOStream>
#include <QtCore/QTextStream>
#include <QtCore/QTextStreamFunction>
#include <QtCore/QTextStreamManipulator>
#include <QtCore/QtGlobal>
#include <QtCore/QThread>
#include <QtCore/QThreadPool>
#include <QtCore/QThreadStorage>
#include <QtCore/QThreadStorageData>
#include <QtCore/QTime>
#include <QtCore/QTimeLine>
#include <QtCore/QTimer>
#include <QtCore/QTimerEvent>
#include <QtCore/QtMsgHandler>
#include <QtCore/QtPlugin>
#include <QtCore/QtPluginInstanceFunction>
#include <QtCore/QTranslator>
#include <QtCore/QTS>
#include <QtCore/QTypeInfo>

#if QT_VERSION < 0x040600//VOXOX CHANGE by Rolando - 2010.01.03 
#include <QtCore/QUintForSize>//VOXOX CHANGE by Rolando 12.29.09 - we don't need it now since version 4.6
#include <QtCore/QUintForType>//VOXOX CHANGE by Rolando 12.29.09 - we don't need it now since version 4.6 
#endif

#include <QtCore/QUrl>
#include <QtCore/QUuid>
#include <QtCore/QVariant>
#include <QtCore/QVariantComparisonHelper>
#include <QtCore/QVariantHash>
#include <QtCore/QVariantList>
#include <QtCore/QVariantMap>
#include <QtCore/QVarLengthArray>
#include <QtCore/QVector>
#include <QtCore/QVectorData>
#include <QtCore/QVectorIterator>
#include <QtCore/QVectorTypedData>
#include <QtCore/QWaitCondition>
#include <QtCore/QWeakPointer>
#include <QtCore/QWriteLocker>
#include <QtCore/QXmlStreamAttribute>
#include <QtCore/QXmlStreamAttributes>
#include <QtCore/QXmlStreamEntityDeclaration>
#include <QtCore/QXmlStreamEntityDeclarations>
#include <QtCore/QXmlStreamEntityResolver>
#include <QtCore/QXmlStreamNamespaceDeclaration>
#include <QtCore/QXmlStreamNamespaceDeclarations>
#include <QtCore/QXmlStreamNotationDeclaration>
#include <QtCore/QXmlStreamNotationDeclarations>
#include <QtCore/QXmlStreamReader>
#include <QtCore/QXmlStreamStringRef>
#include <QtCore/QXmlStreamWriter>
#include <QtCore/Q_INT16>
#include <QtCore/Q_INT32>
#include <QtCore/Q_INT64>
#include <QtCore/Q_INT8>
#include <QtCore/Q_LLONG>
#include <QtCore/Q_LONG>
#include <QtCore/Q_PID>
#include <QtCore/Q_UINT16>
#include <QtCore/Q_UINT32>
#include <QtCore/Q_UINT64>
#include <QtCore/Q_UINT8>
#include <QtCore/Q_ULLONG>
#include <QtCore/Q_ULONG>

//02>25>2009>  02>:35> PM>             3,117> QtCore>


#include <boost/any.hpp>
#include <boost/assert.hpp>
#include <boost/checked_delete.hpp>
#include <boost/config.hpp>
#include <boost/enable_shared_from_this.hpp>
#include <boost/intrusive_ptr.hpp>
#include <boost/iterator.hpp>
#include <boost/next_prior.hpp>
#include <boost/noncopyable.hpp>
#include <boost/operators.hpp>
#include <boost/ref.hpp>
#include <boost/scoped_array.hpp>
#include <boost/scoped_ptr.hpp>
#include <boost/shared_array.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/signal.hpp>
#include <boost/smart_ptr.hpp>
#include <boost/static_assert.hpp>
#include <boost/throw_exception.hpp>
#include <boost/type_traits.hpp>
#include <boost/utility.hpp>
#include <boost/version.hpp>
#include <boost/weak_ptr.hpp>

//These two files must be included BEFORE any boost/serialization files
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>

#include <boost/config/abi/msvc_prefix.hpp>
//#include <boost/config/auto_link.hpp>
#include <boost/config/compiler/visualc.hpp>
#include <boost/config/platform/win32.hpp>
#include <boost/config/requires_threads.hpp>
#include <boost/config/select_compiler_config.hpp>
#include <boost/config/select_platform_config.hpp>
#include <boost/config/select_stdlib_config.hpp>
#include <boost/config/stdlib/dinkumware.hpp>
#include <boost/config/suffix.hpp>
#include <boost/config/user.hpp>

#include <boost/detail/bad_weak_ptr.hpp>
#include <boost/detail/interlocked.hpp>
#include <boost/detail/shared_count.hpp>
#include <boost/detail/sp_counted_base.hpp>
#include <boost/detail/sp_counted_base_w32.hpp>
#include <boost/detail/sp_counted_impl.hpp>
#include <boost/detail/workaround.hpp>

#include <boost/mpl/aux_/adl_barrier.hpp>
#include <boost/mpl/aux_/config/adl.hpp>
#include <boost/mpl/aux_/config/ctps.hpp>
#include <boost/mpl/aux_/config/gcc.hpp>
#include <boost/mpl/aux_/config/intel.hpp>
#include <boost/mpl/aux_/config/lambda.hpp>
#include <boost/mpl/aux_/config/msvc.hpp>
#include <boost/mpl/aux_/config/overload_resolution.hpp>
#include <boost/mpl/aux_/config/preprocessor.hpp>
#include <boost/mpl/aux_/config/static_constant.hpp>
#include <boost/mpl/aux_/config/ttp.hpp>
#include <boost/mpl/aux_/config/workaround.hpp>
//#include <boost/mpl/aux_/integral_wrapper.hpp>
#include <boost/mpl/aux_/lambda_support.hpp>
#include <boost/mpl/aux_/nttp_decl.hpp>
#include <boost/mpl/aux_/preprocessor/params.hpp>
#include <boost/mpl/aux_/static_cast.hpp>
#include <boost/mpl/aux_/template_arity_fwd.hpp>
#include <boost/mpl/bool.hpp>
#include <boost/mpl/bool_fwd.hpp>
#include <boost/mpl/int.hpp>
#include <boost/mpl/int_fwd.hpp>
#include <boost/mpl/integral_c.hpp>
#include <boost/mpl/integral_c_fwd.hpp>
#include <boost/mpl/integral_c_tag.hpp>
#include <boost/mpl/size_t.hpp>
#include <boost/mpl/size_t_fwd.hpp>

#include <boost/preprocessor/arithmetic/add.hpp>
#include <boost/preprocessor/arithmetic/dec.hpp>
#include <boost/preprocessor/arithmetic/inc.hpp>
#include <boost/preprocessor/arithmetic/sub.hpp>
//#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comma_if.hpp>
#include <boost/preprocessor/config/config.hpp>
#include <boost/preprocessor/control/detail/msvc/while.hpp>
#include <boost/preprocessor/control/expr_iif.hpp>
#include <boost/preprocessor/control/if.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/control/while.hpp>
#include <boost/preprocessor/debug/error.hpp>
#include <boost/preprocessor/detail/auto_rec.hpp>
#include <boost/preprocessor/detail/check.hpp>
#include <boost/preprocessor/detail/is_binary.hpp>
#include <boost/preprocessor/facilities/empty.hpp>
#include <boost/preprocessor/inc.hpp>
#include <boost/preprocessor/list/adt.hpp>
#include <boost/preprocessor/list/detail/fold_left.hpp>
#include <boost/preprocessor/list/detail/fold_right.hpp>
#include <boost/preprocessor/list/fold_left.hpp>
#include <boost/preprocessor/list/fold_right.hpp>
#include <boost/preprocessor/list/reverse.hpp>
#include <boost/preprocessor/logical/bitand.hpp>
#include <boost/preprocessor/logical/bool.hpp>
#include <boost/preprocessor/logical/compl.hpp>
#include <boost/preprocessor/punctuation/comma.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/repeat.hpp>
#include <boost/preprocessor/repetition/enum_binary_params.hpp>
#include <boost/preprocessor/repetition/enum_params.hpp>
#include <boost/preprocessor/repetition/repeat.hpp>
#include <boost/preprocessor/repetition/repeat_from_to.hpp>
#include <boost/preprocessor/tuple/eat.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/rem.hpp>

#include <boost/serialization/access.hpp>
#include <boost/serialization/base_object.hpp>
#include <boost/serialization/binary_object.hpp>
#include <boost/serialization/collections_load_imp.hpp>
#include <boost/serialization/collections_save_imp.hpp>
#include <boost/serialization/collection_traits.hpp>
#include <boost/serialization/config.hpp>
#include <boost/serialization/deque.hpp>
//#include <boost/serialization/export.hpp>
#include <boost/serialization/extended_type_info.hpp>
#include <boost/serialization/extended_type_info_no_rtti.hpp>
#include <boost/serialization/extended_type_info_typeid.hpp>
#include <boost/serialization/force_include.hpp>
#include <boost/serialization/hash_map.hpp>
#include <boost/serialization/hash_set.hpp>
#include <boost/serialization/is_abstract.hpp>
#include <boost/serialization/level.hpp>
#include <boost/serialization/level_enum.hpp>
#include <boost/serialization/list.hpp>
#include <boost/serialization/map.hpp>

#include <boost/serialization/nvp.hpp>
#include <boost/serialization/optional.hpp>
#include <boost/serialization/scoped_ptr.hpp>
#include <boost/serialization/serialization.hpp>
#include <boost/serialization/set.hpp>
#include <boost/serialization/shared_ptr.hpp>
//#include <boost/serialization/shared_ptr_132.hpp>		//Conflict with QT::uint8_t
#include <boost/serialization/slist.hpp>
#include <boost/serialization/split_free.hpp>
#include <boost/serialization/split_member.hpp>
#include <boost/serialization/string.hpp>
#include <boost/serialization/tracking.hpp>
#include <boost/serialization/tracking_enum.hpp>

#include <boost/serialization/traits.hpp>
#include <boost/serialization/type_info_implementation.hpp>
#include <boost/serialization/utility.hpp>
#include <boost/serialization/variant.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/version.hpp>
#include <boost/serialization/void_cast.hpp>
#include <boost/serialization/void_cast_fwd.hpp>
#include <boost/serialization/weak_ptr.hpp>

//#include <boost/serialization/detail/shared_count_132.hpp>
//#include <boost/serialization/detail/shared_ptr_132.hpp>
//#include <boost/serialization/detail/shared_ptr_nmt_132.hpp>
#include <boost/serialization/detail/stack_constructor.hpp>


#include <boost/signals/connection.hpp>
//#include <boost/signals/signal_template.hpp>
#include <boost/signals/signal0.hpp>
#include <boost/signals/signal1.hpp>
#include <boost/signals/signal2.hpp>
#include <boost/signals/signal3.hpp>
#include <boost/signals/signal4.hpp>
#include <boost/signals/signal5.hpp>
#include <boost/signals/signal6.hpp>
#include <boost/signals/signal7.hpp>
#include <boost/signals/signal8.hpp>
#include <boost/signals/signal9.hpp>
#include <boost/signals/signal10.hpp>
#include <boost/signals/slot.hpp>
#include <boost/signals/trackable.hpp>
#include <boost/signals/detail/config.hpp>
#include <boost/signals/detail/signals_common.hpp>

#include <boost/thread/detail/config.hpp>
#include <boost/thread/detail/lock.hpp>
#include <boost/thread/exceptions.hpp>
#include <boost/thread/recursive_mutex.hpp>

#include <boost/type_traits/add_const.hpp>
#include <boost/type_traits/add_cv.hpp>
#include <boost/type_traits/add_pointer.hpp>
#include <boost/type_traits/add_reference.hpp>
#include <boost/type_traits/add_volatile.hpp>
#include <boost/type_traits/alignment_of.hpp>
#include <boost/type_traits/broken_compiler_spec.hpp>
#include <boost/type_traits/config.hpp>
#include <boost/type_traits/conversion_traits.hpp>
#include <boost/type_traits/detail/bool_trait_def.hpp>
#include <boost/type_traits/detail/bool_trait_undef.hpp>
#include <boost/type_traits/detail/cv_traits_impl.hpp>
#include <boost/type_traits/detail/false_result.hpp>
#include <boost/type_traits/detail/ice_and.hpp>
#include <boost/type_traits/detail/ice_eq.hpp>
#include <boost/type_traits/detail/ice_not.hpp>
#include <boost/type_traits/detail/ice_or.hpp>
#include <boost/type_traits/detail/is_function_ptr_tester.hpp>
#include <boost/type_traits/detail/is_mem_fun_pointer_tester.hpp>
#include <boost/type_traits/detail/size_t_trait_def.hpp>
#include <boost/type_traits/detail/size_t_trait_undef.hpp>
#include <boost/type_traits/detail/template_arity_spec.hpp>
#include <boost/type_traits/detail/type_trait_def.hpp>
#include <boost/type_traits/detail/type_trait_undef.hpp>
#include <boost/type_traits/detail/yes_no_type.hpp>
#include <boost/type_traits/function_traits.hpp>
#include <boost/type_traits/has_nothrow_assign.hpp>
#include <boost/type_traits/has_nothrow_constructor.hpp>
#include <boost/type_traits/has_nothrow_copy.hpp>
#include <boost/type_traits/has_nothrow_destructor.hpp>
#include <boost/type_traits/has_trivial_assign.hpp>
#include <boost/type_traits/has_trivial_constructor.hpp>
#include <boost/type_traits/has_trivial_copy.hpp>
#include <boost/type_traits/has_trivial_destructor.hpp>
#include <boost/type_traits/has_virtual_destructor.hpp>
#include <boost/type_traits/ice.hpp>
#include <boost/type_traits/integral_constant.hpp>
#include <boost/type_traits/intrinsics.hpp>
#include <boost/type_traits/is_abstract.hpp>
#include <boost/type_traits/is_arithmetic.hpp>
#include <boost/type_traits/is_array.hpp>
#include <boost/type_traits/is_base_and_derived.hpp>
#include <boost/type_traits/is_base_of.hpp>
#include <boost/type_traits/is_class.hpp>
#include <boost/type_traits/is_compound.hpp>
#include <boost/type_traits/is_const.hpp>
#include <boost/type_traits/is_convertible.hpp>
#include <boost/type_traits/is_empty.hpp>
#include <boost/type_traits/is_enum.hpp>
#include <boost/type_traits/is_float.hpp>
#include <boost/type_traits/is_floating_point.hpp>
#include <boost/type_traits/is_function.hpp>
#include <boost/type_traits/is_fundamental.hpp>
#include <boost/type_traits/is_integral.hpp>
#include <boost/type_traits/is_member_function_pointer.hpp>
#include <boost/type_traits/is_member_pointer.hpp>
#include <boost/type_traits/is_pod.hpp>
#include <boost/type_traits/is_pointer.hpp>
#include <boost/type_traits/is_reference.hpp>
#include <boost/type_traits/is_same.hpp>
#include <boost/type_traits/is_scalar.hpp>
#include <boost/type_traits/is_signed.hpp>
#include <boost/type_traits/is_union.hpp>
#include <boost/type_traits/is_unsigned.hpp>
#include <boost/type_traits/is_void.hpp>
#include <boost/type_traits/is_volatile.hpp>
#include <boost/type_traits/remove_cv.hpp>
#include <boost/type_traits/remove_reference.hpp>

#include <boost/utility/addressof.hpp>
#include <boost/utility/base_from_member.hpp>
#include <boost/utility/enable_if.hpp>

#endif	//__cplusplus

#endif	//_WINDOWS