#ifndef __SFP_ERROR_H__
#define __SFP_ERROR_H__

typedef enum sfp_returncode {
	SUCCESS,
	NO_AVAILABLE_PORT,
	CANT_GET_SOCKET,
	CANT_SET_SOCKET_REUSABLE,
	CANT_LISTEN_ON_SOCKET,
	CANT_ACCEPT_CONNECTION,
	TRANSFER_CORRUPTION,
	WRITE_ERROR,
	CANT_CONNECT,
	CONNECTION_TIMED_OUT,
	NETWORK_INITIALIZATION_FAILED,
	CANT_READ_FILE,
	CANT_WRITE_FILE,
	CANT_CLOSE_FILE,
	FILE_SEND_FAILED,
	FILE_RECEIVE_FAILED,
	FAILURE
} sfp_returncode_t;

#endif /* __SFP_ERROR_H__ */

